### ISSUE TITLE
Missing API Key Errors on API Explorer

### ISSUE THREAD

**Issue by kespinola** [holaplex/hub-docs#39]
i get a generic error when i haven't yet entered an api token, could we have a note that that's why i'm getting the error?

![Image](https://user-images.githubusercontent.com/24394839/244209353-47c0548d-c5cb-4fd6-9b31-9f12d746c101.png)

**Comment by mpwsh** [comment]
- Migrated the graphQL playground to [its own repo](https://github.com/holaplex/hub-graphql-playground) and edited the error message + the "GraphiQL" logo on the right side lol


![Image](https://github.com/holaplex/hub-docs/assets/13471075/81dff29e-d7e6-41b1-a04e-6489737dcbd3)


- Created a [ helm chart for the playground ](https://github.com/holaplex/helm-charts/tree/main/charts/hub-graphql-playground)
- configured [CI/CD ](https://argocd.holaplex.tools/applications/prod-graphql-playground?view=tree&conditions=false&resource=)

![Image](https://github.com/holaplex/hub-docs/assets/13471075/2d32ff52-418b-4d24-a8c7-1ac5f0e37fa1)
